language: python
python:
- 3.7.4
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd test
- python -m unittest
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: tQ9sh3Tm1VwDyiRbmnZOa+1yjPACQXMjFQK96MkDwoX7Bw5AyExnhEsnZTbtwCublSXO/6HMZClyIFhavzf7q4bmGNBlZSU4Wgt7A2qZ/HU6AY+mXFeTI7a0OSlOyIHE+W8c6Jc3RYajN5XTSlJRoKIXbeP7uvHDB9WSoGrw13ZfG8WFP2o9a8xuryKXc7KzKsdFbpni6zfTZq6FmOy0a0gmpFfxh2JFO/Oj1NzvDbSvhZ1m/HPpWf6JxyiwXGL7LFnjjCT3Lo8vqKX6ydk+kUTENo6yHKkMT6tNuEHgbVm3Cv7xlRnSSsRIxS8bpmgAx3mQ4Y/GgcYSvdB6nhEaF+CIlbiAFG2v9kD1pn/WS8LCR8UC4f8Oi2C/PQ/Wz+z6lPPyc8ptpepxZPVMQuy11Csmu8FhRHnqmgNk74kUpDqc3ABqRF7X3HSmAnsYrwEX6F/rJel8zblp8JKve+vjvDAZE7+B+WO7UGRcFDCuBCIqidbUnpXUbQfsb5xuI1XCzq/B43t+/vTVaTwF5j04RizHa3Ljo6bJJSRtW0iizKsUt7hHgd2mVPQGz0R619QVDnkS4yId+beU2zpMaFdjVeLE7gQTihLuWJkK9WddfpVoaR5l/fETf1SOn/D8WdoIYWFnBrtOj0+XxZQ6Odjx7SSjWxlGCBEut01ec6HTa14=
